name: Build Site

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site with grotsky
      run: |
        docker run \
        -v ${{ github.workspace }}:/app/ -v ${{ github.workspace }}/_site:/app/_site \
        mliezun/generic-build-and-deploy:latest /bin/bash -c "cd /app && make generate" && \
        cd ${{ github.workspace }} && \
        git add . && \
        git commit -m "New build `date`"
        git checkout -b gh-pages && \
        git push
