name: Build Site

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site with grotsky
      run: |
        cd ${{ github.workspace }} && \
        make generate && \
        git config --global user.email "automated@example.com" && \
        git config --global user.name "Automated Build" && \
        git add . && \
        git commit -m "New build `date`"
        git checkout -b gh-pages && \
        git push --set-upstream origin gh-pages --force
