name: Build Site

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: mliezun/generic-build-and-deploy
    - name: Build the site with grotsky
      run: |
        make generate && \
        cp -r ./_site ${{ github.workspace }}/_site
