name: Build Site

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: mliezun/generic-build-and-deploy:latest

    steps:
    - name: Build the site with grotsky
      run: |
        cd ${{ github.workspace }} && \
        make generate
